### ISSUE TITLE
Conflicts with AVR `util/atomic.h`

### ISSUE THREAD

**Issue by matthijskooijman** [wizard97/SimplyAtomic#1]
If, in a single sketch, both `util/atomic.h` and `SimplyAtomic.h` are included, compilation fails:

	In file included from mjs_firmware.ino:26:0:
	.../avr/include/util/atomic.h: In function 'uint8_t __iSeiRetVal()':
	.../avr/include/util/atomic.h:42:27: error: redefinition of 'uint8_t __iSeiRetVal()'
	 static __inline__ uint8_t __iSeiRetVal(void)
				   ^
	In file included from .../SimplyAtomic/SimplyAtomic.h:9:0,
			 from mjs_firmware.ino:24:
	.../SimplyAtomic/avr.h:15:27: note: 'uint8_t __iSeiRetVal()' previously defined here
	 static __inline__ uint8_t __iSeiRetVal(void)

Similar errors appear for __iCliRetVal and __iRestore. Fixing this
should be a matter of adding a "SimplyAtomic" prefix to all these helper
functions (also, I think `__iSeiRetVal` is not used, and could be
removed?).

It would also be good to add a prefix to the ATOMIC_RESTORESTATE macro,
or remove it altogether and just inline it. I would expect an error
about this macro too, but somehow that doesn't happen here.

On an unrelated note, I see that this code is based on AVR's
util/atomic.h, but the license notice is not preserved, which violates
the license of that code. One could argue that this code is too simple
to apply copyright to, but just keeping the license wouldn't hurt. Now,
there is no license attached at all, which would prevent people from
redistributing (binaries containing) this code.

**Comment by wizard97** [comment]
>If, in a single sketch, both util/atomic.h and SimplyAtomic.h are included, compilation fails:

Yeah, I noticed this on my own a while ago and never got around to fixing it. I just did as you suggested and prefixed all custom methods and macros with `SA_`

> On an unrelated note, I see that this code is based on AVR's
util/atomic.h, but the license notice is not preserved, which violates
the license of that code. One could argue that this code is too simple
to apply copyright to, but just keeping the license wouldn't hurt. Now,
there is no license attached at all, which would prevent people from
redistributing (binaries containing) this code.

Fixed this as well! Thanks for pointing it out. I put the entire project under a BSD license as well in order to be compatible with the AVR's methods I pulled from util/atomic.h.
